### PR TITLE
Strict checking for conversion of strings to DateTime objects

### PR DESCRIPTION
**Pull request by HaraldJoerg**
This PR compensates for changes in DateTime::Format::Strptime.  That module now allows minutes to be omitted from the timezone, and per default ignores trailing garbage.  Unfortunately, this makes a test with an invalid time stamp run without throwing up - which it should.

As of DateTime::Format::Strptime version 1.71, there's a "strict" parameter which does no longer allow trailing garbage.  This is now set, the version requirement added to the code.

I have not yet committed stuff for the Changes file because I doubt this can be automatically merged with the other PR coming soon.

### CODE REVIEW

**Comment by HaraldJoerg** [comment]
I just noted that the CI tests croak because dzil complains about a duplicate LICENSE file.  You have one in your code base, and dzil tries to create its own.

I can reproduce that:

[DZ] attempt to add LICENSE multiple times; added by: filename set by GatherDir (Dist::Zilla::Plugin::GatherDir line 225); encoded_content added by @Starter/GatherDir (Dist::Zilla::Plugin::GatherDir line 226); content added by @Starter/License (Dist::Zilla::Plugin::License line 37)
aborting; duplicate files would be produced at /home/haj/perl5/perlbrew/perls/perl-5.28.0/lib/site_perl/5.28.0/Dist/Zilla/App/Command/build.pm line 107.

**Comment by heytrav** [comment]
you can get rid of the license file in code if that helps. I'm happy to use the one generated by dzil. I remember running into this issue before on my ParseUtil::Domain module as well, once up on a time.

**Comment by HaraldJoerg** [comment]
I have removed the LICENSE file in the repository, but also added a COPYRIGHT AND LICENSE section in your main module to satisfy CPANTS kwalitee check.  I've also added to the Changes file.

With these changes in place, the PR #6 is no longer needed.  I did _not_ do the same changes for that PR.

Looks as if the distribution now passes the CI test.  Cheers!

**Comment by heytrav** [comment]
Ok this looks good to me. Happy to merge

**Pull request merged**
